### ISSUE TITLE
Recalculate '.mobile-mega-menu' min-height on window resize?

### ISSUE THREAD

**Issue by vanarsdale** [Blake-C/mobile-mega-menu#4]
Would it be possible to add a recalculated min-height for the '.mobile-mega-menu.open' on screen resize?

**Comment by Blake-C** [comment]
I've made an update to the plugin that will call a function on window resize to recalculate the tallest item in the menu and update the min-height value. 

https://github.com/Blake-C/mobile-mega-menu/commit/2b2b5a5afa53b9d91edf76eafe866e6470dfed2c

Please pull the latest version of the plugin and let me know if this solves your issue. If you are using npm I published v1.0.3 with the changes.

**Comment by vanarsdale** [comment]
Very cool, and thank you — that worked well.
